# Generated by Django 2.2.11 on 2020-05-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='app.Message'),
        ),
    ]
